package pt.ua.sd.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;

import pt.ua.sd.distribution.DistributionClient;

/**
 * Graphical launcher with settings menus
 * 
 * @author André Prata
 * @author Eriksson Monteiro
 */
public class Faina extends javax.swing.JFrame implements Observer {

	/**
     * 
     */
	private static final long serialVersionUID = -5683722366666441886L;

	/** Creates new form Faina */
	public Faina() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		width = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		height = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		campaigns = new javax.swing.JTextField();
		companies = new javax.swing.JTextField();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		boats = new javax.swing.JTextField();
		boatCapacity = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		boatSleep = new javax.swing.JTextField();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		shoals = new javax.swing.JTextField();
		shoalSize = new javax.swing.JTextField();
		minDetectable = new javax.swing.JTextField();
		growingFactor = new javax.swing.JTextField();
		maxCatchPercentage = new javax.swing.JTextField();
		ecoSystem = new javax.swing.JTextField();
		jLabel24 = new javax.swing.JLabel();
		shoalMoves = new javax.swing.JTextField();
		shoalSleep = new javax.swing.JTextField();
		jLabel23 = new javax.swing.JLabel();
		logFile = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel14 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		width.setText("11");

		jLabel15.setText("Height:");

		height.setText("11");

		jLabel1.setText("Width:");

		jLabel16.setText("Campaigns:");

		campaigns.setText("5");

		companies.setText("2");

		jLabel17.setText("Companies:");

		jLabel18.setText("Boats each:");

		boats.setText("5");

		boatCapacity.setText("100");

		jLabel2.setText("Capacity:");

		jLabel4.setText("Sleep:");

		boatSleep.setText("333");

		jLabel19.setText("Schools:");

		jLabel20.setText("Initial fish:");

		jLabel6.setText("Min. detectable:");

		jLabel22.setText("Max. catch %:");

		jLabel12.setText("Growing factor:");

		jLabel21.setText("Ecosystem:");

		shoals.setText("5");

		shoalSize.setText("2000");

		minDetectable.setText("10");

		growingFactor.setText("2");

		maxCatchPercentage.setText("80");

		ecoSystem.setText("0.001");

		jLabel24.setForeground(new java.awt.Color(102, 0, 0));
		jLabel24.setText("Shoal moves:");

		shoalMoves.setText("40");

		shoalSleep.setText("666");

		jLabel23.setText("Sleep:");

		logFile.setText("log.txt");

		jButton1.setText("Browse...");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel14.setText("Log file:");

		jButton3.setText("Configure servers");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton2.setText("Run");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel3.setText("Log");

		jLabel5.setText("Ocean");

		jLabel7.setText("Shoals");

		jLabel8.setText("Boats");

		jLabel9.setText("DirOper");

		jLabel10.setText("tboats");

		jLabel11.setText("tshoals");

		jLabel13.setText("tdiropers");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3).addComponent(jLabel5).addComponent(jLabel7)
												.addComponent(jLabel8).addComponent(jLabel9).addComponent(jLabel10)
												.addComponent(jLabel11).addComponent(jLabel13))
								.addContainerGap(74, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel3)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel5)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel7)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel8)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel9)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel10)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel11)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel13).addContainerGap(20, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(60, 60, 60)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jButton3,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										208,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jButton2,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										91,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(jLabel14)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										logFile,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										205,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jButton1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										91,
																										javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel22)
																												.addComponent(
																														jLabel6)
																												.addComponent(
																														jLabel20)
																												.addComponent(
																														jLabel19)
																												.addComponent(
																														jLabel1)
																												.addComponent(
																														jLabel15)
																												.addComponent(
																														jLabel16)
																												.addComponent(
																														jLabel17)
																												.addComponent(
																														jLabel18)
																												.addComponent(
																														jLabel12)
																												.addComponent(
																														jLabel21))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														ecoSystem,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)
																												.addComponent(
																														shoals,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)
																												.addComponent(
																														shoalSize,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)
																												.addComponent(
																														minDetectable,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)
																												.addComponent(
																														maxCatchPercentage,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)
																												.addComponent(
																														growingFactor,
																														javax.swing.GroupLayout.Alignment.TRAILING,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)
																												.addComponent(
																														boatCapacity,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)
																												.addGroup(
																														javax.swing.GroupLayout.Alignment.TRAILING,
																														layout.createSequentialGroup()
																																.addComponent(
																																		boats,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		100,
																																		Short.MAX_VALUE)
																																.addGap(1,
																																		1,
																																		1))
																												.addComponent(
																														companies,
																														javax.swing.GroupLayout.Alignment.TRAILING,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)
																												.addComponent(
																														campaigns,
																														javax.swing.GroupLayout.Alignment.TRAILING,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)
																												.addComponent(
																														height,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)
																												.addComponent(
																														width,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														101,
																														Short.MAX_VALUE)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(jLabel2)
																								.addGap(162, 162, 162)))
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addGroup(
																														javax.swing.GroupLayout.Alignment.LEADING,
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.TRAILING)
																																				.addComponent(
																																						jLabel24)
																																				.addComponent(
																																						jLabel23))
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						shoalMoves,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						95,
																																						Short.MAX_VALUE)
																																				.addComponent(
																																						shoalSleep,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						95,
																																						Short.MAX_VALUE)))
																												.addComponent(
																														jPanel1,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(39, 39, 39))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(58, 58, 58)
																								.addComponent(jLabel4)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										boatSleep,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										47,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						width,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jLabel1))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(jLabel2)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														height,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jLabel15))
																								.addGap(1, 1, 1)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														campaigns,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jLabel16))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														companies,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jLabel17))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														boats,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														jLabel18))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										boatCapacity,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(shoals, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel19)
												.addComponent(jLabel4)
												.addComponent(boatSleep, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(shoalSize, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel20))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(minDetectable, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel6))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(maxCatchPercentage,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel22))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(jLabel24)
																				.addComponent(
																						shoalMoves,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(jLabel23)
																				.addComponent(
																						shoalSleep,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						growingFactor,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jLabel12))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						ecoSystem,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jLabel21))))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(logFile, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jButton1)
												.addComponent(jLabel14))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2).addComponent(jButton3))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		new SimulationLaunch(this).setVisible(true);
	}// GEN-LAST:event_jButton3ActionPerformed

	String rmiserveraddress = "192.168.8.171";
	String rmiserverport = "22145"; // this and the next port will be used!
	String mlogserveaddress = "192.168.8.177";
	String mlogserveport = "22140";
	String moceanseraddress = "192.168.8.177";
	String moceanserport = "22141";
	String mshoalseraddress = "192.168.8.173";
	String mshoalserport = "22142";
	String mdiropersaddress = "192.168.8.174";
	String mdiropersport = "22143";
	String mboatservaddress = "192.168.8.175";
	String mboatservport = "22144";
	String tboatservaddress = "192.168.8.176";
	String tshoalseraddress = "192.168.8.178";
	String tdiropersaddress = "192.168.8.180";

	public void setServersConfigurations(String[] config) {
		assert (config.length == 15);
		rmiserveraddress = config[0];
		rmiserverport = config[1];
		mlogserveaddress = config[2];
		mlogserveport = config[3];
		moceanseraddress = config[4];
		moceanserport = config[5];
		mshoalseraddress = config[6];
		mshoalserport = config[7];
		mdiropersaddress = config[8];
		mdiropersport = config[9];
		mboatservaddress = config[10];
		mboatservport = config[11];
		tboatservaddress = config[12];
		tshoalseraddress = config[13];
		tdiropersaddress = config[14];
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		final RemoteObserver obs = new RemoteObserver(8);
		setObservable(obs);
		obs.startMonitoring(2000);
		new Thread(new Runnable() {

			@Override
			public void run() {
				DistributionClient.setObservable(obs);
				DistributionClient.main(new String[] { width.getText(), height.getText(), campaigns.getText(),
						companies.getText(), boats.getText(), boatCapacity.getText(), boatSleep.getText(),
						shoals.getText(), shoalSize.getText(), minDetectable.getText(), maxCatchPercentage.getText(),
						growingFactor.getText(), ecoSystem.getText(), shoalMoves.getText(), shoalSleep.getText(),
						logFile.getText(), rmiserveraddress, rmiserverport, mlogserveaddress, mlogserveport,
						moceanseraddress, moceanserport, mshoalseraddress, mshoalserport, mdiropersaddress,
						mdiropersport, mboatservaddress, mboatservport, tboatservaddress, tshoalseraddress,
						tdiropersaddress });
			}
		}).start();

	}// GEN-LAST:event_jButton2Ac127.0.0.1tionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		JFileChooser chooser = new JFileChooser();
		int returnVal = chooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			logFile.setText(chooser.getSelectedFile().getAbsolutePath());
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new Faina().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField boatCapacity;
	private javax.swing.JTextField boatSleep;
	private javax.swing.JTextField boats;
	private javax.swing.JTextField campaigns;
	private javax.swing.JTextField companies;
	private javax.swing.JTextField ecoSystem;
	private javax.swing.JTextField growingFactor;
	private javax.swing.JTextField height;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField logFile;
	private javax.swing.JTextField maxCatchPercentage;
	private javax.swing.JTextField minDetectable;
	private javax.swing.JTextField shoalMoves;
	private javax.swing.JTextField shoalSize;
	private javax.swing.JTextField shoalSleep;
	private javax.swing.JTextField shoals;
	private javax.swing.JTextField width;
	// End of variables declaration//GEN-END:variables
	Observable observable;

	public void setObservable(Observable observable) {
		observable.addObserver(this);
		this.observable = observable;
	}

	@Override
	public void update(Observable o, Object arg) {
		if (o != observable) {
			System.out.println("Contacted by wrong observable");
			return;
		}

		if (arg instanceof String[]) {
			String[] params = (String[]) arg;
			Graphics graphics = jPanel1.getGraphics();
			int x = 100, y = 20 + 20 * (Integer.valueOf(params[1])), radius = 7;

			if (params[0].compareToIgnoreCase("alive") == 0) {
				graphics.drawOval(x - radius, y - radius, 2 * radius, 2 * radius);
				graphics.setColor(Color.WHITE);
				graphics.fillOval(x - radius, y - radius, 2 * radius, 2 * radius);
				try {
					Thread.sleep(150);
				} catch (InterruptedException ex) {
					Logger.getLogger(Faina.class.getName()).log(Level.SEVERE, null, ex);
				}
				graphics.drawOval(x - radius, y - radius, 2 * radius, 2 * radius);
				graphics.setColor(Color.GREEN);
				graphics.fillOval(x - radius, y - radius, 2 * radius, 2 * radius);

			} else {
				graphics.drawOval(x - radius, y - radius, 2 * radius, 2 * radius);
				graphics.setColor(Color.RED);
				graphics.fillOval(x - radius, y - radius, 2 * radius, 2 * radius);
			}
		}
	}
}
